runtime: python
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "path/to/serviceAccountKey.json"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

